<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DependencySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'id' => 1,
                'name' => 'Dirección Técnica',
                'internal_code' => '02-03',
                'parent_id' => 11,
                'user_id' => null,
                'created_at' => '2024-05-22 22:15:00',
                'updated_at' => '2024-05-22 22:15:00',
            ],
            [
                'id' => 2,
                'name' => 'Dirección de Recursos Humanos',
                'internal_code' => '02-02',
                'parent_id' => 11,
                'user_id' => null,
                'created_at' => '2024-05-22 22:15:00',
                'updated_at' => '2024-05-22 22:15:00',
            ],
            [
                'id' => 3,
                'name' => 'Dirección de Administración y Presupuesto',
                'internal_code' => '02-01',
                'parent_id' => 11,
                'user_id' => null,
                'created_at' => '2024-05-22 22:15:00',
                'updated_at' => '2024-05-22 22:15:00',
            ],
            [
                'id' => 4,
                'name' => 'Dirección de Servicio Juridicos',
                'internal_code' => '01-02',
                'parent_id' => 8,
                'user_id' => null,
                'created_at' => '2024-05-22 22:15:00',
                'updated_at' => '2024-05-22 22:15:00',
            ],
            [
                'id' => 5,
                'name' => 'Dirección de Determinación de Responsabilidades',
                'internal_code' => '01-04',
                'parent_id' => null,
                'user_id' => null,
                'created_at' => '2024-05-22 22:15:00',
                'updated_at' => '2024-05-22 22:15:00',
            ],
            [
                'id' => 6,
                'name' => 'Dirección de Control de la Administración Central y Poderes Estadales',
                'internal_code' => '01-06',
                'parent_id' => 8,
                'user_id' => null,
                'created_at' => '2024-05-22 22:15:00',
                'updated_at' => '2024-05-22 22:15:00',
            ],
            [
                'id' => 7,
                'name' => 'Dirección de Control de la Administración Descentralizada',
                'internal_code' => '01-04',
                'parent_id' => 8,
                'user_id' => null,
                'created_at' => '2024-05-22 22:15:00',
                'updated_at' => '2024-05-22 22:15:00',
            ],
            [
                'id' => 8,
                'name' => 'Despacho del Contralor',
                'internal_code' => '01',
                'parent_id' => null,
                'user_id' => null,
                'created_at' => '2024-05-22 22:15:00',
                'updated_at' => '2024-05-22 22:15:00',
            ],
            [
                'id' => 9,
                'name' => 'Unidad de Auditoria Interna',
                'internal_code' => '01-03',
                'parent_id' => 8,
                'user_id' => null,
                'created_at' => '2024-05-22 22:15:00',
                'updated_at' => '2024-05-22 22:15:00',
            ],
            [
                'id' => 10,
                'name' => 'Dirección de Atención al Ciudadano y Control Comunitario',
                'internal_code' => '01-01',
                'parent_id' => 8,
                'user_id' => null,
                'created_at' => '2024-05-22 22:15:00',
                'updated_at' => '2024-05-22 22:15:00',
            ],
            [
                'id' => 11,
                'name' => 'Despacho del Sub-Contralor',
                'internal_code' => '02',
                'parent_id' => null,
                'user_id' => null,
                'created_at' => '2024-05-22 22:15:00',
                'updated_at' => '2024-05-22 22:15:00',
            ],
            [
                'id' => 12,
                'name' => 'División de Servicios Generales',
                'internal_code' => '02-01-03',
                'parent_id' => 3,
                'user_id' => null,
                'created_at' => '2024-05-22 22:15:00',
                'updated_at' => '2024-05-22 22:15:00',
            ],
            [
                'id' => 13,
                'name' => 'Asistencia al Despacho',
                'internal_code' => '01-00-01',
                'parent_id' => 8,
                'user_id' => null,
                'created_at' => '2024-05-22 22:15:00',
                'updated_at' => '2024-05-22 22:15:00',
            ],
            [
                'id' => 14,
                'name' => 'División de Control de Gestión (D)',
                'internal_code' => '01-05-01',
                'parent_id' => 7,
                'user_id' => null,
                'created_at' => '2024-05-22 22:15:00',
                'updated_at' => '2024-05-22 22:15:00',
            ],
            [
                'id' => 15,
                'name' => 'División de Control de Gestión (C)',
                'internal_code' => '01-06-01',
                'parent_id' => 6,
                'user_id' => null,
                'created_at' => '2024-05-22 22:15:00',
                'updated_at' => '2024-05-22 22:15:00',
            ],
            [
                'id' => 16,
                'name' => 'División de Administración de Personal',
                'internal_code' => '02-02-01',
                'parent_id' => 2,
                'user_id' => null,
                'created_at' => '2024-05-22 22:15:00',
                'updated_at' => '2024-05-22 22:15:00',
            ],
            [
                'id' => 17,
                'name' => 'División de Relaciones Laborales',
                'internal_code' => '02-02-02',
                'parent_id' => 2,
                'user_id' => null,
                'created_at' => '2024-05-22 22:15:00',
                'updated_at' => '2024-05-22 22:15:00',
            ],
            [
                'id' => 18,
                'name' => 'División de Administración y Tesoreria',
                'internal_code' => '02-01-01',
                'parent_id' => 3,
                'user_id' => null,
                'created_at' => '2024-05-22 22:15:00',
                'updated_at' => '2024-05-22 22:15:00',
            ],
            [
                'id' => 19,
                'name' => 'División de Presupuesto y Contabilidad',
                'internal_code' => '02-01-02',
                'parent_id' => 3,
                'user_id' => null,
                'created_at' => '2024-05-22 22:15:00',
                'updated_at' => '2024-05-22 22:15:00',
            ],
            [
                'id' => 20,
                'name' => 'División de Planificación Organización y Desarrollo',
                'internal_code' => '02-03-02',
                'parent_id' => 1,
                'user_id' => null,
                'created_at' => '2024-05-22 22:15:00',
                'updated_at' => '2024-05-22 22:15:00',
            ],
            [
                'id' => 21,
                'name' => 'División de Telemática',
                'internal_code' => '02-03-01',
                'parent_id' => 1,
                'user_id' => null,
                'created_at' => '2024-05-22 22:15:00',
                'updated_at' => '2024-05-22 22:15:00',
            ],
            [
                'id' => 22,
                'name' => 'Dirección de Comunicación y Relaciones Públicas',
                'internal_code' => '02-07',
                'parent_id' => 8,
                'user_id' => null,
                'created_at' => '2024-05-22 22:15:00',
                'updated_at' => '2024-05-22 22:15:00',
            ],
            [
                'id' => 23,
                'name' => 'Coordinación de Transporte, Seguridad y Mantenimiento',
                'internal_code' => '055',
                'parent_id' => 12,
                'user_id' => null,
                'created_at' => '2024-05-22 22:15:00',
                'updated_at' => '2024-05-22 22:15:00',
            ],
            [
                'id' => 24,
                'name' => 'División de Bienes',
                'internal_code' => '02-01-04',
                'parent_id' => 3,
                'user_id' => null,
                'created_at' => '2024-05-22 22:15:00',
                'updated_at' => '2024-05-22 22:15:00',
            ],
        ];

        DB::table('dependencies')->insert($data);
    }
}
